"/usr/local/bastille/jails/mainjail/root/usr/local" "/usr/local" ro
"/home/app1" "/root" rw
"/home/app1/configs" "/etc/app1" rw
# Don't forget to escape spaces. Special characters will likely also cause an issue, so i'd avoid em.
"/home/app1/music\ files" "/mnt/music"
